// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CommentNewController from "./comment_new_controller"
application.register("comment-new", CommentNewController)

import EditPasswordController from "./edit_password_controller"
application.register("edit-password", EditPasswordController)

import ResetFormController from "./reset_form_controller"
application.register("reset-form", ResetFormController)

import RichEditorController from "./rich_editor_controller"
application.register("rich-editor", RichEditorController)

import RichTextPreviewController from "./rich_text_preview_controller"
application.register("rich-text-preview", RichTextPreviewController)

import TwinkleNewCommentController from "./twinkle_new_comment_controller"
application.register("twinkle-new-comment", TwinkleNewCommentController)
