// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AdvanceSearchController from "./advance_search_controller"
application.register("advance-search", AdvanceSearchController)

import CommentNewController from "./comment_new_controller"
application.register("comment-new", CommentNewController)

import EditPasswordController from "./edit_password_controller"
application.register("edit-password", EditPasswordController)

import FadeoutController from "./fadeout_controller"
application.register("fadeout", FadeoutController)

import ResetFormController from "./reset_form_controller"
application.register("reset-form", ResetFormController)

import RichEditorController from "./rich_editor_controller"
application.register("rich-editor", RichEditorController)

import RichTextPreviewController from "./rich_text_preview_controller"
application.register("rich-text-preview", RichTextPreviewController)

import RichtextSummaryController from "./richtext_summary_controller"
application.register("richtext-summary", RichtextSummaryController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import SearchDialogController from "./search_dialog_controller"
application.register("search-dialog", SearchDialogController)

import TwinkleNewCommentController from "./twinkle_new_comment_controller"
application.register("twinkle-new-comment", TwinkleNewCommentController)
