version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: bbs_db
    volumes:
      - postgres_data_bbs:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
  app:
    build:
      context: .
      dockerfile: ./Dockerfile-zh
    env_file:
      - .env
    volumes:
      - app_storage:/rails/storage
    depends_on:
      - db
    ports:
      - 3000:3000

volumes:
  postgres_data_bbs: {}
  app_storage: {}
    
    