version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: bbs_db
    volumes:
      - postgres_data_bbs:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432

  redis:
    build: ./redis
    container_name: bbs_redis
    ports:
      - 6397:6379

  app:
    build:
      context: .
      dockerfile: ${APP_DOCKERFILE}
    env_file:
      - .env
    volumes:
      - app_storage:/rails/storage
    depends_on:
      - db
      - redis
    ports:
      - 3000:3000
  web:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
      args:
        - SERVER_NAME=${SERVER_NAME}
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app

volumes:
  postgres_data_bbs: {}
  app_storage: {}
    
    